export enum Categoria {
    TODAS = "TODAS",
    TRANSPORTE = "TRANSPORTE",
    EDUCACAO = "EDUCACAO",
    SAUDE = "SAUDE",
    MORADIA = "MORADIA",
    MEIO_AMBIENTE = "MEIO_AMBIENTE",
    CULTURA_LAZER = "CULTURA_LAZER",
    SEGURANCA = "SEGURANCA",
    EMPREGO = "EMPREGO",
    SERVICOS_PUBLICOS = "SERVICOS_PUBLICOS",
    ASSUNTOS_GERAIS = "ASSUNTOS_GERAIS"
}
